### ISSUE TITLE
White screen error after civicrm entity update

### ISSUE THREAD

**Issue by lkuttner** [eileenmcnaughton/nz.co.fuzion.entitysetting#14]
After updating to civicrm_entity 7.x-2.3, when attempting to manage CiviCRM 5.33.5 on Drupal 7.78 we get a white screen website encountered an unexpected error and Error: Call to undefined method CRM_Core_BAO_Cache::getItem() in CRM_Entitysetting_BAO_EntitySetting::getSettingSpecification() (line 81 of /var/www/cascade/prod/nesea.org/htdocs/sites/all/extensions/nz.co.fuzion.entitysetting/CRM/Entitysetting/BAO/EntitySetting.php).  Disabling this extension resolves this.

**Comment by seamuslee001** [comment]
I would suggest you update to version 1.4 which you can download here https://github.com/eileenmcnaughton/nz.co.fuzion.entitysetting/releases/tag/1.4

**Comment by lkuttner** [comment]
That fixed it.  Thank you very much.  I did not realize there was an update available-- it was not showing on our extensions page.
